version: 2.1
jobs:
  publish-to-dev-repo:
    docker:
      - image: circleci/openjdk:8u265-jdk
    working_directory: ~/app
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Install jFrog CLI
          command: |
            curl -fL https://getcli.jfrog.io | sh
            chmod +x jfrog
            mkdir -p ~/.local/bin
            mv jfrog ~/.local/bin
      - run:
          name: Show Tools version
          command: |
            javac -version
            java -version
            jfrog --version
            docker --version
            gradle --version
      - run:
          name: Docker login artifactory
          command: |
            docker login -u $ARTIFACTORY_USER -p $ARTIFACTORY_APIKEY $ARTIFACTORY_DOCKER_URL
            docker login -u $ARTIFACTORY_USER -p $ARTIFACTORY_APIKEY $ARTIFACTORY_DOCKER_DEV_URL
      # restore saved caches
      - restore_cache:
          keys:
            - babl-gradle-wrapper-{{ .Branch }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - babl-gradle-wrapper-{{ .Branch }}
            - babl-gradle-wrapper-develop
      - restore_cache:
          keys:
            - babl-gradle-cache-{{ .Branch }}-{{ checksum "build.gradle" }}
            - babl-gradle-cache-{{ .Branch }}
            - babl-gradle-cache-develop


      - run:
          name: Initialize gradle wrapper
          command: |
            ./gradlew wrapper --gradle-version 6.7.1
      - run:
          name: Clean build and publish the project artifacts
          command: |
            ./gradlew :jfrogInfo > jfrogInfo.txt
            [[ $CIRCLE_BRANCH == "develop" ]] || [[ $CIRCLE_BRANCH == release/* ]] || [[ $CIRCLE_BRANCH == "master" ]] && publish_opts="artifactoryPublish configArtifactory"
            ./gradlew clean build -x checkLicenseMain -x test -x checkstyleMain -x checkstyleJmh $publish_opts $grade_build_opts --info --refresh-dependencies


      - save_cache:
          paths:
            - ~/.gradle/wrapper/
          key: babl-gradle-wrapper-{{ .Branch }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      - save_cache:
          paths:
            - ~/.gradle/caches/
          key: babl-gradle-cache-{{ .Branch }}-{{ checksum "build.gradle" }}

      - store_test_results:
          path: ~/app/build/test-results
      - persist_to_workspace:
          root: ~/app
          paths:
            - build

workflows:
  version: 2
  build-flow:
    jobs:
      - publish-to-dev-repo:
          context: deriv-non-prod
          filters:
            branches:
              only:
                - develop
                - /^feature\/.*/
                - /^release\/.*/
